# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - gem_cutter_controller

  gem_cutter_controller:
    type: FollowJointTrajectory
    joints:
      - joint1_base_yaw
      - joint2_shoulder_pitch
      - joint3_elbow_pitch
      - joint4_wrist_pitch
      - joint5_wrist_roll
      - joint6_tool_yaw
    action_ns: follow_joint_trajectory
    default: true